apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP_NAME}
  namespace: ${OPENSHIFT_NAMESPACE}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-cs
  resources:
    requests:
      storage: 1Gi
